### ISSUE TITLE
Use plugins like markdown-it

### ISSUE THREAD

**Issue by endlesskwazar** [modood/gulp-markdown-github-style#3]
Hi. good project. Сan i use plugins like in markdown-it
`var md = require('markdown-it')()
            .use(plugin1)
            .use(plugin2, opts, ...)
            .use(plugin3);`
Sorry, im neewbie to JavaScript, but you wrapped creation of MarkdownIt  object in function, thats accepts only options and i cant figure out what to do. Thx for help.

**Comment by modood** [comment]
@endlesskwazar Hi. I'm glad you liked it. But this is a very simple project and it doesn't have much features. So maybe you should fork it and make your own changes.
